export {resolvers as resolversUser} from "./User.js"
export {resolvers as resolversProduct} from "./Product.js"
export {resolvers as resolversPermission} from "./Permission.js"
export {resolvers as resolversNotifications} from "./Notifications.js"
export {resolvers as resolversOrder} from "./Order.js"
export {resolvers as resolversGeneral} from "./General.js"