export {typeDefs as typeDefsUser} from "./User.js"
export {typeDefs as typeDefsProduct} from "./Product.js"
export {typeDefs as typeDefsPermission} from "./Permission.js"
export {typeDefs as typeDefsNotifications} from "./Notifications.js"
export {typeDefs as typeDefsOrder} from "./Order.js"
export {typeDefs as typeDefsGeneral} from "./General.js"